Repository nimona/go-nimona, pull requests merged in 2018-10, with the labels that each got.

#147 Refactor cli into daemon/client
  Gopkg.lock
  api/api.go
  api/handlers_blocks.go
  api/handlers_local.go
  api/handlers_peers.go
  api/handlers_providers.go
  api/handlers_streams.go
  api/renderer_cbor.go
  api/renderer_select.go
  cmd/nimona/cmd/block.go
  cmd/nimona/cmd/blockGet.go
  cmd/nimona/cmd/blockList.go
  cmd/nimona/cmd/blockListen.go
  cmd/nimona/cmd/blockSend.go
  cmd/nimona/cmd/daemon.go
  cmd/nimona/cmd/daemon_bootstraps.go
  cmd/nimona/cmd/peer.go
  cmd/nimona/cmd/peerGet.go
  cmd/nimona/cmd/peerList.go
  cmd/nimona/cmd/peerLocal.go
  cmd/nimona/cmd/root.go
  cmd/nimona/main.go
  net/exchange.go
  storage/storage_disk.go
Labels: Status: In Review

#152 Add dockerfile
  .dockerignore
  Dockerfile
  Gopkg.lock
Labels: Status: In Review

#153 Allow direct dialling a peer by address
  api/handlers_blocks.go
  api/handlers_streams.go
  cmd/nimona/cmd/daemon.go
  cmd/nimona/cmd/daemon_bootstraps.go
  dht/dht.go
  dht/dht_query.go
  net/exchange.go
  net/exchange_test.go
  net/handshake_syn.go
  net/handshake_syn_ack.go
  net/manager.go
  net/network.go
  net/payload_forwarded.go
  peers/addressbook.go
  peers/peerinfo.go
  telemetry/telemetry.go
Labels: Status: In Review

#158 Slightly reformat readme
  README.md
Labels: Status: In Review, Type: Documentation

#157 Add static assets to release bins
  .gitattributes
  Dockerfile
  Gopkg.lock
  Makefile
  api/api.go
  api/assets.go
  api/assets/index.html
  api/assets_generator.go
  api/assets_vfsdata.go
  api/handlers_streams.go
  api/serve_fs.go
  cmd/nimona/cmd/daemon.go
Labels: Status: In Review, Type: Enhancement

#156 Add basic info on how to run nimona
  README.md
Labels: Status: In Review, Type: Documentation

#161 Specify own hostname from cli option
  cmd/nimona/cmd/daemon.go
  cmd/nimona/cmd/root.go
  net/network.go
  net/utils.go
  peers/addressbook.go
Labels: Priority: Medium, Status: In Review, Type: Enhancement
