Repository nimona/go-nimona, pull requests merged in 2018-09, with the labels that each got.

#133 Make embedded blocks b58 strings
  blocks/block.go
  blocks/decode.go
  blocks/decode_test.go
  blocks/encode.go
  blocks/encode_test.go
  blocks/key.go
  blocks/marshaler.go
  blocks/sign.go
  blocks/signature.go
  blocks/signature_test.go
  blocks/unmarshal.go
  cmd/nimona/main.go
  net/exchange.go
  peers/addressbook.go
  peers/peerinfo.go
Labels: review

#134 New bootstrap nodes and cli, logging fixes, cleanup
  cmd/bootstraps/main.go
  cmd/nimona/main.go
  net/network.go
  peers/addressbook.go
  peers/addressbook_keys.go
Labels: review

#131 Add metrics
  Gopkg.lock
  cmd/nimona/main.go
  net/collectable_connection.go
  net/exchange.go
  net/exchange_mock.go
  net/telemetry.go
  telemetry/collectable.go
  telemetry/collector.go
  telemetry/collector_influx.go
  telemetry/telemetry.go
Labels: review

#138 Remove encoding of nested blocks
  blocks/block.go
  blocks/pack.go
  blocks/pack_test.go
  blocks/sign.go
  blocks/unpack.go
  blocks/unpack_test.go
  cmd/nimona/main.go
  crypto/signature.go
  crypto/signature_test.go
  dht/dht.go
  peers/addressbook_keys.go
  peers/peerinfo_private.go
Labels: review

#139 Fix goreleaser
  .circleci/config.yml
  .goreleaser.yml
Labels: review

#142 Refactor connections and exchange
  .vscode/launch.json
  Gopkg.lock
  Gopkg.toml
  api/api.go
  blocks/block.go
  blocks/pack.go
  blocks/pack_test.go
  blocks/registry.go
  blocks/sign.go
  blocks/unknown.go
  blocks/unpack.go
  blocks/unpack_test.go
  cmd/nimona/main.go
  dht/dht.go
  dht/dht_query.go
  dht/dht_test.go
  dht/message.go
  dht/peerinfo_request.go
  dht/peerinfo_response.go
  dht/provider.go
  dht/provider_request.go
  dht/provider_response.go
  net/connection.go
  net/exchange.go
  net/exchange_test.go
  net/handshake_ack.go
  net/handshake_syn.go
  net/handshake_syn_ack.go
  net/manager.go
  net/network.go
  net/payload_forwarded.go
  net/payload_handshake.go
  net/telemetry.go
  peers/addressbook.go
  telemetry/collector_influx.go
Labels: Priority: Critical, Status: In Review, Type: Bug

#144 Add HTTP and WS api
  Gopkg.lock
  api/api.go
  api/index.html
  blocks/block.go
  blocks/pack.go
  blocks/pack_test.go
  blocks/unpack.go
  blocks/unpack_test.go
  cmd/nimona/main.go
  dht/dht.go
  dht/dht_query.go
  net/exchange.go
  telemetry/telemetry.go
Labels: Status: In Review
